const VITE_APP_GOOGLE_MAP = import.meta.env.VITE_APP_GOOGLE_MAP ?? ''
const VITE_APP_FIREBASE_API_KEY = import.meta.env.VITE_APP_FIREBASE_API_KEY ?? ''
const VITE_APP_FIREBASE_AUTH_DOMAIN = import.meta.env.VITE_APP_FIREBASE_AUTH_DOMAIN ?? ''
const VITE_APP_FIREBASE_PROJECT_ID = import.meta.env.VITE_APP_FIREBASE_PROJECT_ID ?? ''
const VITE_APP_FIREBASE_STORAGE_BUCKET = import.meta.env.VITE_APP_FIREBASE_STORAGE_BUCKET ?? ''
const VITE_APP_FIREBASE_MESSAGING_SENDER_ID =
  import.meta.env.VITE_APP_FIREBASE_MESSAGING_SENDER_ID ?? ''
const VITE_APP_FIREBASE_APP_ID = import.meta.env.VITE_APP_FIREBASE_APP_ID ?? ''
const VITE_APP_FIREBASE_MEASUREMENT_ID = import.meta.env.VITE_APP_FIREBASE_MEASUREMENT_ID ?? ''
export {
  VITE_APP_GOOGLE_MAP,
  VITE_APP_FIREBASE_API_KEY,
  VITE_APP_FIREBASE_AUTH_DOMAIN,
  VITE_APP_FIREBASE_PROJECT_ID,
  VITE_APP_FIREBASE_STORAGE_BUCKET,
  VITE_APP_FIREBASE_MESSAGING_SENDER_ID,
  VITE_APP_FIREBASE_APP_ID,
  VITE_APP_FIREBASE_MEASUREMENT_ID,
}
